plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.travelsoft.tickets'
    compileSdk 34

    defaultConfig {
        applicationId "com.travelsoft.tickets"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    buildFeatures {
        buildConfig true
    }

    def localProperties = new Properties()
    localProperties.load(new FileInputStream(rootProject.file("local.properties")))

    signingConfigs {
        release {
            storeFile file(localProperties.getProperty("SACTEL_KEYSTORE"))
            storePassword localProperties.getProperty("SACTEL_STORE_PASSWORD")
            keyAlias localProperties.getProperty("SACTEL_KEY_ALIAS")
            keyPassword localProperties.getProperty("SACTEL_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
    implementation 'org.java-websocket:Java-WebSocket:1.5.7'
}